### PR TITLE
FastMM FullDebugMode workaround

### PR DESCRIPTION
**Pull request by gabr42**
We are experiencing crashes in FRibbon.LoadSettingsFromStream and FRibbon.SaveSettingsToStream if FastMM's FullDebugMode is enabled. This commit disables those two calls if FullDebugMode is defined.

### CODE REVIEW

**Comment by joachimmarder** [comment]
What was the exact error? This $ifdef just makes symptoms disappear but does not seem to solve the actual problem.

**Comment by gabr42** [comment]
The problem is that when FullDebugMode is enabled and you call one of those two functions, you often get error 

Project ettwin.exe raised exception class $C0000005 with message 'access violation at 0x0f59a8bb: read of address 0x80808088'.

with stack trace similar to:

:0f59a8bb ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f43012f ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f4325cd ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f59a8c8 ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f4443eb ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f4c0934 ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f4beadc ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f493ac5 ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f495e63 ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f443fcd ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f443aa4 ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f443a63 ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f42dc2e ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f42d794 ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f443794 ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f42b7e3 ; C:\WINDOWS\SysWOW64\UIRibbon.dll
:0f438c82 ; C:\WINDOWS\SysWOW64\UIRibbon.dll
UIRibbon.TUIRibbon.LoadSettings($7F7D03A0)
UIRibbon.TUIRibbon.LoadSettings('C:\Users\gabr\AppData\Roaming\FAB Teletext Editor\frmEttwinMain_RibbonOptions.xml')
UIRibbon.TUIRibbon.LoadRibbonSettings
UIRibbon.TUIRibbon.Load
UIRibbon.TUIRibbon.WMPaint((15, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()))
Vcl.Controls.TControl.WndProc((15, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()))
Vcl.Controls.TWinControl.WndProc((15, 0, 0, 0, 0, 0, (), 0, 0, (), 0, 0, ()))
Vcl.Controls.TWinControl.MainWndProc(???)
System.Classes.StdWndProc(2890516,15,0,0)
:75fc4923 user32.CharNextW + 0x73
:75fa4790 ; C:\WINDOWS\SysWOW64\user32.dll
:75fa4370 ; C:\WINDOWS\SysWOW64\user32.dll
:75fab179 ; C:\WINDOWS\SysWOW64\user32.dll
:779aae46 ntdll.KiUserCallbackDispatcher + 0x36
:75fa3e50 user32.DispatchMessageW + 0x10
Vcl.Forms.TApplication.ProcessMessage(???)
:0062beec TApplication.ProcessMessage + $F8

I discussed this with Piette and apparently it is a very deep issue with FastMM which should catch UnloadLibrary calls and invalidate its internal cache when a DLL is unloaded. As this is not done at the moment, internal address mapping of FullDebugMode gets invalid and then weird things happen.

**Comment by joachimmarder** [comment]
Can this be reproduced with the included sample projects?

**Comment by gabr42** [comment]
I'll check.

**Comment by gabr42** [comment]
I could repeat it with `02 Text Pad with Action List`.

Steps to reproduce:
- Remove mad* units from the .dpr.
- Add `FastMM4` to the top of the .dpr's uses list.
- Define FullDebugMode.
- Rebuild.
- Delete the settings file `FormMain_RibbonOptions.xml` from the disk.
- Run the program (under debugger).
- Close the program.
- Run the program again (under debugger).

It crashes in LoadSettings.

Tried it three times, crashed in all three attempts.

**Comment by joachimmarder** [comment]
It would be great if you could add the repro steps to the issue in case you are going to open one. 

There is one problem though with your pull request: We do not use an external FastMM any more because most of its feature have meanwhile been integrated into the Delphi itself. But we still use the define FullDebugMode for other purposes.

So using $ifdef FullDebugMode to decide not to save ribbon settings would not work well for us.

**Comment by gabr42** [comment]
That's a problem, indeed. What do you recommend?

**Comment by joachimmarder** [comment]
> What do you recommend?

Not sure. I'm not a fan of writing code that tries to hide the symptoms of a bug that origins from somewhere else, at least not in the official repository. It's usually better to fix the bug than trying to hide its symptoms.

**Comment by gabr42** [comment]
Actually, with the proposed Options property (Issue #13) this IFDEF is not needed anymore as it could be equally well put into the user code.

I'll create an issue for the problem, then close this pull request. (Please keep it open until then so that I don't forget to create an issue ...)

**Pull request closed without merging**
